language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

python:
  - "3.5"

sudo: false

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev # provides unbuffer utility
      - python-lxml # because pip installation is slow

branches:
  only:
    - "12.0"
    - "13.0"
    - "14.0"

env:
  global:
    - VERSION="12.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0" WKHTMLTOPDF_VERSION="0.12.4"

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
